### ISSUE TITLE
Where is RTS message stored? How receiving node knows about it?

### ISSUE THREAD

**Issue by etam** [freenet/plugin-Freemail#34]
https://github.com/freenet/plugin-Freemail/blob/3f37853c0d646b0518626e340b57ad1e105009b0/docs/spec/spec.tex#L85-L86

Is this true?

I'm studying how Freemail works and for testing I set up two nodes and send a message from one to the other. All I had to do before sending message, was to manually add trust for the other node. I didn't solve any CAPTCHA for that. The receiving node is even configured not to publish WoT CAPTCHAs. How did it knew it received a message?

**Comment by etam** [comment]
So I checked the source code, and this is what I found:

- `mailpage` file contains a random `rtsksk` value
- client that wants to send RTS message creates a KSK key that is composed of:
  - `rtsksk` value
  - current date
  - a natural number, called "slot"

Freemail loops over slot numbers, trying to find a first one that makes an unused KSK key.

**Comment by ArneBab** [comment]
This is a typical method in Freenet to allow contacting someone who is not already subscribed to a USK you publish. The KSK breaks the chicken-egg problem that you can only watch a key you know about by creating a key anyone can upload to.
